### ISSUE TITLE
Attach custom RAG

### ISSUE THREAD

**Issue by marcos99-sap** [Conv-AI/Convai-Web-SDK-Old#7]
Hi,

I want to know if it's possible to attach a specific custom RAG to ConvAI, in order to control the information in a better way.

Thanks

**Comment by AirSurfer09** [comment]
You can put everything in knowledge bank. But no custom RAG as of now.

**Comment by marcos99-sap** [comment]
> You can put everything in knowledge bank. But no custom RAG as of now.

Thanks @AirSurfer09  for the answer.

Unfortunately Knowledge Bank seeems to be not so perfect. I have observed that several times the character goes to allucination or is not able to retrieve the correct information.

have someone some tips in order to have a better performance?
Thanks in advance
